#!/bin/bash
# Installation de chan_quectel pour Asterisk
# Détecte automatiquement le type de modem et installe le bon fork
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/colors.sh"
source "$SCRIPT_DIR/lib/logging.sh"
source "$SCRIPT_DIR/lib/utils.sh"

BUILD_DIR="/usr/src/chan_quectel"

log_header "chan_quectel Installation"

require_root

# Check if Asterisk is installed
if ! command_exists asterisk; then
    log_error "Asterisk is not installed. Run 03-install-asterisk.sh first."
    exit 1
fi

# Detect modem type
log_info "Detecting GSM modems..."

MODEM_TYPE=""
MODEM_USB_ID=""

if lsusb | grep -q "1e0e:"; then
    MODEM_TYPE="sim7600"
    MODEM_USB_ID=$(lsusb | grep "1e0e:" | head -1)
    log_success "Detected SIM7600 modem: $MODEM_USB_ID"
elif lsusb | grep -q "2c7c:"; then
    MODEM_TYPE="ec25"
    MODEM_USB_ID=$(lsusb | grep "2c7c:" | head -1)
    log_success "Detected EC25 modem: $MODEM_USB_ID"
else
    log_warn "No supported modem detected. Installing for SIM7600 by default."
    log_info "Supported modems: SIM7600 (1e0e:), EC25/Quectel (2c7c:)"
    MODEM_TYPE="sim7600"
fi

# Install build dependencies
log_info "Installing build dependencies..."
DEPS=(
    build-essential
    cmake
    automake
    autoconf
    libtool
    pkg-config
    libasound2-dev
    libsqlite3-dev
)
install_packages "${DEPS[@]}"

# Get Asterisk version for headers
ASTERISK_VERSION=$(asterisk -V 2>/dev/null | grep -oP '\d+' | head -1)
log_info "Detected Asterisk version: $ASTERISK_VERSION"

# Check if Asterisk headers are installed
if [[ ! -d "/usr/include/asterisk" ]]; then
    log_warn "Asterisk headers not found in /usr/include/asterisk"
    log_info "Checking /usr/src for Asterisk source..."

    AST_SRC=$(find /usr/src -maxdepth 2 -type d -name "asterisk-*" 2>/dev/null | head -1)
    if [[ -n "$AST_SRC" && -d "$AST_SRC/include/asterisk" ]]; then
        log_info "Copying headers from $AST_SRC..."
        mkdir -p /usr/include/asterisk
        cp -r "$AST_SRC/include/asterisk/"* /usr/include/asterisk/
        log_success "Asterisk headers installed"
    else
        log_error "Cannot find Asterisk headers. Ensure Asterisk was compiled from source."
        exit 1
    fi
fi

# Cleanup old build
[[ -d "$BUILD_DIR" ]] && rm -rf "$BUILD_DIR"
ensure_dir "$BUILD_DIR"
cd "$BUILD_DIR"

# Clone the appropriate fork
case "$MODEM_TYPE" in
    sim7600)
        # RoEdAl fork with CMake - works for SIM7600
        REPO="https://github.com/RoEdAl/asterisk-chan-quectel.git"
        COMMIT="37b566f"
        BUILD_SYSTEM="cmake"
        log_info "Using RoEdAl fork (CMake) for SIM7600..."
        ;;
    ec25)
        # IchthysMaranatha fork with autoconf - works for EC25
        REPO="https://github.com/IchthysMaranatha/asterisk-chan-quectel.git"
        COMMIT=""  # Use latest
        BUILD_SYSTEM="autoconf"
        log_info "Using IchthysMaranatha fork (autoconf) for EC25..."
        ;;
esac

log_info "Cloning repository..."
git clone "$REPO" chan_quectel >> "$LOG_FILE" 2>&1
cd chan_quectel

# Checkout specific commit if needed
if [[ -n "$COMMIT" ]]; then
    git checkout "$COMMIT" >> "$LOG_FILE" 2>&1
    log_info "Checked out commit $COMMIT"
fi

# Build
log_info "Building chan_quectel..."

case "$BUILD_SYSTEM" in
    cmake)
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release .. >> "$LOG_FILE" 2>&1
        make -j"$(nproc)" >> "$LOG_FILE" 2>&1
        make install >> "$LOG_FILE" 2>&1
        ;;
    autoconf)
        ./bootstrap >> "$LOG_FILE" 2>&1 || autoreconf -i >> "$LOG_FILE" 2>&1
        ./configure --with-astversion="$ASTERISK_VERSION" >> "$LOG_FILE" 2>&1
        make -j"$(nproc)" >> "$LOG_FILE" 2>&1
        make install >> "$LOG_FILE" 2>&1
        ;;
esac

log_success "chan_quectel built and installed"

# Create basic quectel.conf if not exists
QUECTEL_CONF="/etc/asterisk/quectel.conf"
if [[ ! -f "$QUECTEL_CONF" ]]; then
    log_info "Creating default quectel.conf..."

    cat > "$QUECTEL_CONF" << EOF
; chan_quectel configuration
; Generated by Homenichat installer on $(date)

[general]
interval = 15
smsdb = /var/lib/asterisk/smsdb
csmsttl = 600

[defaults]
context = from-gsm
group = 0
autodeletesms = no
resetquectel = yes
usecallingpres = yes
callingpres = allowed_passed_screen

; Modem settings - WILL BE AUTO-CONFIGURED
; Run modem detection to configure automatically:
;   /opt/homenichat/scripts/modem/detect-modem.sh

; Example for SIM7600:
;[quectel-sim7600]
;data = /dev/ttyUSB2
;audio = /dev/ttyUSB4
;rxgain = 2
;txgain = 2
;slin16 = yes

; Example for EC25:
;[quectel-ec25]
;data = /dev/ttyUSB2
;audio = /dev/ttyUSB1
;rxgain = 3
;txgain = -5
;slin16 = no
EOF

    chown asterisk:asterisk "$QUECTEL_CONF"
    log_success "Created $QUECTEL_CONF"
fi

# Load module in Asterisk
log_info "Loading chan_quectel module..."
asterisk -rx "module load chan_quectel.so" >> "$LOG_FILE" 2>&1 || true

# Verify
if asterisk -rx "quectel show devices" 2>/dev/null | grep -q "quectel"; then
    log_success "chan_quectel loaded and detecting modems"
else
    log_info "chan_quectel loaded (no modems configured yet)"
fi

# Cleanup
if [[ "${CLEANUP_BUILD:-1}" == "1" ]]; then
    log_info "Cleaning up build files..."
    rm -rf "$BUILD_DIR"
fi

log_success "chan_quectel installation complete for $MODEM_TYPE"
log_info "Next step: Run modem detection to configure your modem"
log_info "  /opt/homenichat/scripts/modem/detect-modem.sh"
