#!/bin/bash
# Configuration d'Asterisk pour Homenichat (sans FreePBX)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/colors.sh"
source "$SCRIPT_DIR/lib/logging.sh"
source "$SCRIPT_DIR/lib/utils.sh"

ASTERISK_DIR="/etc/asterisk"
HOMENICHAT_CONFIG="${HOMENICHAT_CONFIG_DIR:-/etc/homenichat}"

log_header "Asterisk Configuration"

require_root

# Check if Asterisk is installed
if ! command_exists asterisk; then
    log_error "Asterisk is not installed. Run 03-install-asterisk.sh first."
    exit 1
fi

# Backup existing configuration
log_info "Backing up existing configuration..."
backup_file "$ASTERISK_DIR/pjsip.conf"
backup_file "$ASTERISK_DIR/extensions.conf"
backup_file "$ASTERISK_DIR/http.conf"
backup_file "$ASTERISK_DIR/manager.conf"

# Generate passwords if not set
AMI_PASSWORD="${AMI_PASSWORD:-$(random_password 16)}"
WEBRTC_PASSWORD="${WEBRTC_PASSWORD:-$(random_password 16)}"

# Configure AMI (Asterisk Manager Interface)
log_info "Configuring AMI..."
cat > "$ASTERISK_DIR/manager.conf" << EOF
; Asterisk Manager Interface configuration
; Generated by Homenichat on $(date)

[general]
enabled = yes
port = 5038
bindaddr = 127.0.0.1
displayconnects = no
timestampevents = yes

[homenichat]
secret = $AMI_PASSWORD
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan,originate
write = system,call,log,verbose,command,agent,user,config,dtmf,reporting,cdr,dialplan,originate
writetimeout = 5000
eventfilter = !Event: RTCPSent
eventfilter = !Event: RTCPReceived
EOF

# Configure HTTP for WebSocket (WebRTC)
log_info "Configuring HTTP server for WebRTC..."
cat > "$ASTERISK_DIR/http.conf" << EOF
; HTTP server configuration (for WebRTC)
; Generated by Homenichat on $(date)

[general]
enabled = yes
bindaddr = 0.0.0.0
bindport = 8088
tlsenable = yes
tlsbindaddr = 0.0.0.0:8089
tlscertfile = $HOMENICHAT_CONFIG/ssl/cert.pem
tlsprivatekey = $HOMENICHAT_CONFIG/ssl/key.pem
EOF

# Configure PJSIP
log_info "Configuring PJSIP..."
cat > "$ASTERISK_DIR/pjsip.conf" << EOF
; PJSIP configuration for Homenichat
; Generated by Homenichat on $(date)

; ===== TRANSPORTS =====

[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[transport-wss]
type = transport
protocol = wss
bind = 0.0.0.0:8089

; ===== TEMPLATES =====

[endpoint-webrtc](!)
type = endpoint
context = from-webrtc
disallow = all
allow = opus
allow = ulaw
allow = alaw
webrtc = yes
dtls_auto_generate_cert = yes
media_encryption = dtls
media_encryption_optimistic = yes
ice_support = yes
rtcp_mux = yes
direct_media = no
force_rport = yes
rewrite_contact = yes

[auth-template](!)
type = auth
auth_type = userpass

[aor-template](!)
type = aor
max_contacts = 5
remove_existing = yes
qualify_frequency = 60

; ===== EXTENSIONS =====
; Extensions will be auto-generated by Homenichat
; See: /etc/asterisk/pjsip_homenichat.conf

#include pjsip_homenichat.conf
EOF

# Create empty includes file
touch "$ASTERISK_DIR/pjsip_homenichat.conf"

# Configure Extensions (Dialplan)
log_info "Configuring dialplan..."
cat > "$ASTERISK_DIR/extensions.conf" << EOF
; Dialplan configuration for Homenichat
; Generated by Homenichat on $(date)

[general]
static = yes
writeprotect = no
autofallthrough = yes
clearglobalvars = no
priorityjumping = no

[globals]
; Global variables

; ===== CONTEXTS =====

[from-webrtc]
; Calls from WebRTC clients (mobile app, PWA)
exten => _X.,1,NoOp(WebRTC call from \${CALLERID(all)} to \${EXTEN})
 same => n,Goto(from-internal,\${EXTEN},1)

[from-internal]
; Internal routing for all outbound calls

; Local extensions (2XXX)
exten => _2XXX,1,NoOp(Call to local extension \${EXTEN})
 same => n,Dial(PJSIP/\${EXTEN},30)
 same => n,Hangup()

; French mobile (06, 07)
exten => _0[67]XXXXXXXX,1,NoOp(French mobile call to \${EXTEN})
 same => n,Set(CALLERID(num)=\${CALLERID(num)})
 same => n,Dial(Quectel/g0/\${EXTEN},60,tT)
 same => n,Hangup()

; French landline (01-05, 08-09)
exten => _0[1-5]XXXXXXXX,1,NoOp(French landline call to \${EXTEN})
 same => n,Dial(Quectel/g0/\${EXTEN},60,tT)
 same => n,Hangup()

exten => _0[89]XXXXXXXX,1,NoOp(French special number to \${EXTEN})
 same => n,Dial(Quectel/g0/\${EXTEN},60,tT)
 same => n,Hangup()

; International (00...)
exten => _00.,1,NoOp(International call to \${EXTEN})
 same => n,Dial(Quectel/g0/\${EXTEN},60,tT)
 same => n,Hangup()

; Emergency (SAMU, Police, Pompiers)
exten => _1X,1,NoOp(Emergency call to \${EXTEN})
 same => n,Dial(Quectel/g0/\${EXTEN},60)
 same => n,Hangup()

[from-gsm]
; Incoming calls from GSM modem
exten => s,1,NoOp(Incoming GSM call from \${CALLERID(num)})
 same => n,Set(CALLERID(name)=\${CALLERID(num)})
 ; Notify Homenichat about incoming call
 same => n,AGI(agi://127.0.0.1:4573/incoming_call)
 ; Ring all extensions
 same => n,Dial(PJSIP/2001&PJSIP/2002&PJSIP/2003,30,tT)
 same => n,VoiceMail(100@default,u)
 same => n,Hangup()

exten => _+X.,1,Goto(s,1)
exten => _X.,1,Goto(s,1)

; ===== CUSTOM EXTENSIONS =====
; Additional dialplan rules from Homenichat
#include extensions_homenichat.conf
EOF

# Create empty includes file
touch "$ASTERISK_DIR/extensions_homenichat.conf"

# Create SSL directory and self-signed certificate if not exists
log_info "Setting up SSL certificates..."
ensure_dir "$HOMENICHAT_CONFIG/ssl"

if [[ ! -f "$HOMENICHAT_CONFIG/ssl/cert.pem" ]]; then
    log_info "Generating self-signed SSL certificate..."

    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "$HOMENICHAT_CONFIG/ssl/key.pem" \
        -out "$HOMENICHAT_CONFIG/ssl/cert.pem" \
        -subj "/CN=homenichat/O=Homenichat/C=FR" \
        >> "$LOG_FILE" 2>&1

    chmod 600 "$HOMENICHAT_CONFIG/ssl/key.pem"
    chown -R asterisk:asterisk "$HOMENICHAT_CONFIG/ssl"

    log_success "Self-signed certificate generated"
else
    log_info "SSL certificate already exists"
fi

# Set permissions
chown -R asterisk:asterisk "$ASTERISK_DIR"

# Save AMI credentials to Homenichat config
log_info "Saving AMI credentials..."
if [[ -f "$HOMENICHAT_CONFIG/.env" ]]; then
    # Remove old AMI settings
    sed -i '/^AMI_/d' "$HOMENICHAT_CONFIG/.env"

    # Add new settings
    cat >> "$HOMENICHAT_CONFIG/.env" << EOF

# Asterisk AMI
AMI_HOST=127.0.0.1
AMI_PORT=5038
AMI_USER=homenichat
AMI_PASSWORD=$AMI_PASSWORD
EOF
fi

# Reload Asterisk
log_info "Reloading Asterisk configuration..."
asterisk -rx "core reload" >> "$LOG_FILE" 2>&1

# Verify
sleep 2

if asterisk -rx "pjsip show transports" 2>/dev/null | grep -q "transport"; then
    log_success "PJSIP transports configured"
fi

if asterisk -rx "manager show connected" 2>/dev/null; then
    log_success "AMI configured"
fi

log_success "Asterisk configuration complete"
log_info "AMI User: homenichat"
log_info "AMI Password: $AMI_PASSWORD"
log_info "WebRTC WSS: wss://<your-ip>:8089/ws"
